POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
  "email": "juan123@gmail.com",
  "password": "juan123"
}

###

POST http://localhost:3001/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Juan",
  "lastName": "Lopez",
  "email": "juan123@gmail.com",
  "password": "juan123"
}

###

GET http://localhost:3001/api/v1/task/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg0MjkwMzJmNjNmODhmMTI0ZTk2OGQiLCJpYXQiOjE3MTk5MzcyODgsImV4cCI6MTcyMDAyMzY4OH0.cF_q-rTjgOjBqpBN3VwDL58vRU9nptwhgjLCx7HA1VI

###

GET http://localhost:3001/api/v1/task/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg0MjkwMzJmNjNmODhmMTI0ZTk2OGQiLCJpYXQiOjE3MTk5MzcyODgsImV4cCI6MTcyMDAyMzY4OH0.cF_q-rTjgOjBqpBN3VwDL58vRU9nptwhgjLCx7HA1VI

###

POST http://localhost:3001/api/v1/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg0MjkwMzJmNjNmODhmMTI0ZTk2OGQiLCJpYXQiOjE3MTk5MzcyODgsImV4cCI6MTcyMDAyMzY4OH0.cF_q-rTjgOjBqpBN3VwDL58vRU9nptwhgjLCx7HA1VI

{
  "title": "Prueba 1",
  "description": "Prueba 1",
  "priority": "BAJA"
}

###

PUT http://localhost:3001/api/v1/task/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg0MjkwMzJmNjNmODhmMTI0ZTk2OGQiLCJpYXQiOjE3MTk5MzcyODgsImV4cCI6MTcyMDAyMzY4OH0.cF_q-rTjgOjBqpBN3VwDL58vRU9nptwhgjLCx7HA1VI

{
  "title": "Prueba 1 Modificado",
  "description": "Prueba 1 Modificado",
  "priority": "ALTA"
}

###

DELETE  http://localhost:3001/api/v1/task/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg0MjkwMzJmNjNmODhmMTI0ZTk2OGQiLCJpYXQiOjE3MTk5MzcyODgsImV4cCI6MTcyMDAyMzY4OH0.cF_q-rTjgOjBqpBN3VwDL58vRU9nptwhgjLCx7HA1VI

